disabled_rules:
  - conditional_binding_cascade
  - cyclomatic_complexity
  - force_cast
  - force_try
  - line_length
  - variable_name

opt_in_rules:
  - colon                           # Colons should be next to the identifier when specifying a type
  - comma                           # There should be no space before and one after any comma
  - conditional_binding_cascade     # Repeated `let` statements in conditional binding cascade should be avoided
  - empty_count                     # Prefer checking `isEmpty` over comparing `count` to zero
  - leading_whitespace              # Files should not contain leading whitespace
  - legacy_cggeometry_functions     # Struct extension properties and methods are preferred over legacy functions
  - legacy_constant                 # Struct-scoped constants are preferred over legacy global constants
  - opening_brace                   # Opening braces should be preceded by a single space and on the same line as the declaration
  - return_arrow_whitespace         # Return arrow and return type should be separated by a single space or on a separate line
  - statement_position              # Else and catch should be on the same line, one space after the previous declaration
  - trailing_newline                # Files should have a single trailing newline
  - trailing_semicolon              # Lines should not have trailing semicolons
  - trailing_whitespace             # Lines should not have trailing whitespace
  - type_name                       # Type name should only contain alphanumeric characters, start with an uppercase character 
                                    # and span between 3 and 40 characters in length

excluded: # paths to ignore during linting.
  - Carthage

# Rule Configuration
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 60
    error: 80
